### ISSUE TITLE
How to apply Plink format in ngsTools (ped/map data as input)

### ISSUE THREAD

**Issue by MaoYafei** [mfumagalli/ngsTools#10]
Dear all,

I use angsd and ngsTools to do PCA analysis and I found the PCA analysis (by angsd) are not similar with my previous study (by Plink). I tried lots of parameters in angsd and found the results are highly depended on the angsd parameters which are mainly about quality control. So I am wondering how I could apply plink output (ped/map data) to ngsTools as input?

Best, 
Yafei

**Comment by fgvieira** [comment]
Hi Yafei,

in theory, you could convert plink output so that ngsTools could read it, but I fail to see the goal.
ngsTools is aimed at low coverage data and, as such, uses genotype likelihoods directly instead of calling genotypes (that you'll have to do if you convert to plink format).

What is the coverage of your data?

best,

**Comment by MaoYafei** [comment]
Hi Vieira,

Thanks for your reply, average coverage of my data is about 8x so that I would like to try ANGSD and ngsTools. But I also try to use gatk and plink to call genotype and compare that result with ngsTools'. I found that the results are almost similar except for one individual and so I would like to test whether the result is related with the sites I applied there. According to Fumagalli's help in google group, I used -sites option and figure it out. 
BTW, I did not apply outgroup in ngsTools, do you think it has affect on the genotype likelihoods estimating?
Thanks a lot~

Best, 
Yafei
