### ISSUE TITLE
PCA analysis with unlinked sites

### ISSUE THREAD

**Issue by beausoleilmo** [mfumagalli/ngsTools#30]
I was wondering why the tutorial is not making a PCA on pruned or unlinked sites in the [TUTORIAL.md](https://github.com/mfumagalli/ngsTools/blob/master/TUTORIAL.md). It is mentioned in the inbreeding part, but not for PCA. How would this be performed?

**Comment by mfumagalli** [comment]
Hi, it is because ngsLD arrived way after our initial implementations of PCA and we never updated this tutorial. I suggest you use ngsLD to get a list of putatively unlinked sites (please see documentation and tips on ngsLD's github repo) and then feed this list to a software for PCA. I recommend PCangsd http://popgen.dk/software/index.php/PCAngsd.

**Comment by beausoleilmo** [comment]
OK! I saw on [ngsLD](https://github.com/fgvieira/ngsLD) that the script `scripts/prune_ngsLD.py` can get a `.pos` file which looks like this: 

```
NC_044592.1:3801
NC_044592.1:3810
NC_044592.1:3811
NC_044592.1:95051
NC_044592.1:95061
[...]
```

But then it would not match the `.geno` file. Nowhere I was able to find a way to use the unlinked sites with a `.geno` file. Should the `.geno` file be subsetted? I saw that PCAngsd can use PLINK input files, but not ngsLD files. You seem to suggest that it is possible to directly use the ngsLD output in PCAngsd, but I don't see this being possible with the options shown. 

For PCAngsd I have:
`pcangsd -b my.beagle.gz -t 4 -o ./pcangsd/output.pcangsd --minMaf 0.05 --selection --admix  -e 4 --sites_save`
